name: Check Tweets

on:
  schedule:
    - cron: '*/15 * * * *'  # Automatically runs every 15 minutes
  workflow_dispatch:        # Enables a manual "Run Workflow" button on GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bot Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TWITTER_TARGET_USER: ${{ secrets.TWITTER_TARGET_USER }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
        run: python main.py

      - name: Save Last Checked Tweet ID
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_tweet_id.txt || true
          git commit -m "Update last checked tweet ID" || exit 0
          git push
